In [1]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for row in a:
    for col in row:
        print(col, end=" ")
    print()


1 2 3 
4 5 6 
7 8 9 


In [10]:
students_grades = [
    ["John", 7.5],
    ["Mary", 9.0],
    ["Bob", 6.0],
    ["Alice", 8.0],
    ["Mike", 3.0],
    ["Anna", 10.0],
    ["Tom", 5.0],
    ["Jane", 7.5],
]

for row in students_grades:
    if row[1] >= 8.0:
        print(row[0], row[1])


Mary 9.0
Alice 8.0
Anna 10.0


In [3]:
count = 0
for row in students_grades:
    if row[1] >= 4:
        count += 1
print(count)

NameError: name 'students_grades' is not defined

In [8]:
import random as rd

a = []
for i in range(5):
    a.append(rd.sample(range(1, 100), 5))
print(a)

[[24, 28, 60, 47, 37], [34, 8, 21, 97, 94], [1, 40, 55, 37, 34], [10, 89, 46, 13, 42], [45, 84, 44, 37, 22]]


In [5]:
print(a[3:5])

[[91, 16, 3, 42, 25], [40, 94, 15, 29, 79]]


In [6]:
print(a[1:4])

[[37, 99, 75, 58, 55], [22, 85, 53, 86, 45], [91, 16, 3, 42, 25]]


In [13]:
n = int(input('Enter n:'))

b = a[n]
print(b)
print(max(b), min(b))

[10, 89, 46, 13, 42]
89 10


In [14]:
n = int(input('Enter n:'))

b = a[n]
print(b)
print(sum(b))

[1, 40, 55, 37, 34]
167


In [16]:
n = int(input('Enter n:'))

b = a[n]
print(b)
print(sorted(b))

[10, 89, 46, 13, 42]
[10, 13, 42, 46, 89]


In [2]:
import numpy as np

a = [1,2,3]
b = np.array(a)
print(a, type(a))
print(b, type(b))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [23]:
a = np.arange(50,101,5)
print(a)

a = np.linspace(2,5,15)
print(a)

a = np.logspace(1,10,10 ,base=3,dtype=int)
print(a)

[ 50  55  60  65  70  75  80  85  90  95 100]
[2.         2.21428571 2.42857143 2.64285714 2.85714286 3.07142857
 3.28571429 3.5        3.71428571 3.92857143 4.14285714 4.35714286
 4.57142857 4.78571429 5.        ]
[    3     9    27    81   243   729  2187  6561 19683 59049]


In [24]:
zeros = np.zeros(10)
print(zeros)

ones = np.ones((3,3))
print(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
a = np.random.randint(10,100,5)
print(a)
print(a ** 10)

[25 13 35 10 42]
[ 1977800241   419538377  1528444521  1410065408 -2051251200]


In [4]:
a = np.random.randint(10,100,10)
print(a)

print(a[a % 10 == 3])
print(a[a // 10 == 5])


[99 63 44 13 90 10 23 83 19 69]
[63 13 23 83]
[]


In [96]:
a = np.random.randint(10,100,(5,5))
print(a)

[[87 36 14 22 62]
 [53 89 58 59 93]
 [45 49 48 48 80]
 [24 31 74 87 17]
 [24 66 85 15 42]]
