In [2]:
def my_max(a, b):
    if a > b:
        return a
    return b
print(my_max(5, 7)) # work with integers
print(my_max('a', 'b')) # work with strings
print(my_max(5.0, 4.2)) # work with floats

7
b
5.0


In [3]:
print(my_max(5.0, 5)) 

5


In [4]:
# pass by value vs pass by reference
def double(x):
    x = x * 2
    print(x)

In [5]:
x = 6
double(x) # => 12
print(x)  # => 6

12
6


In [6]:
import numpy as np
x = np.array([1, 2, 3])
double(x) # => [2 4 6]
print(x)  # => [1 2 3]

[2 4 6]
[1 2 3]


In [7]:
def double_list(x):
    for i in range(len(x)):
        x[i] = x[i] * 2
    print(x)

In [8]:
x = np.array([1, 2, 3])
double_list(x) # => [2 4 6]
print(x)  # => [2 4 6]

[2 4 6]
[2 4 6]
4*5*6


In [9]:
def my_sort(a, asc=True):
    n = len(a)
    if asc:
        for i in range(n - 1):
            for j in range(i + 1, n):
                if a[j] < a[i]:
                    a[i], a[j] = a[j], a[i]
    else:
        for i in range(n - 1):
            for j in range(i + 1, n):
                if a[j] > a[i]:
                    a[i], a[j] = a[j], a[i]

In [10]:
numbers = [np.random.randint(0, 100) for i in range(10)]
print(numbers)
my_sort(numbers)
print(numbers)
my_sort(numbers, asc=False)
print(numbers)

[52, 40, 78, 17, 93, 28, 23, 63, 51, 48]
[17, 23, 28, 40, 48, 51, 52, 63, 78, 93]
[93, 78, 63, 52, 51, 48, 40, 28, 23, 17]


In [11]:
def demo_keyword(x, n=10, s='hello'):
    print('x =', x)
    print('n =', n)
    print('s =', s)

In [12]:
def my_sum(*items):
    print(type(items))
    s = 0
    for i in items:
        s += i
    return s

In [13]:
def min_max(a, b):
    if a > b:
        return b, a
    return a, b
mi, ma = min_max(50, 7)
print(mi, ma)

_, ma = min_max(50, 7)
print(ma)

7 50
50


In [30]:
#search for x in items, return true if found, false otherwise. if abs = true, search |x|
def search(items, x, abs=False):
    if abs:
        if -x in items or x in items:
            return True 
        return False
    else:
        if x in items:
            return True
        return False

In [35]:
a = [-1,-2,-4,3]
search(a,-3, abs=True)

True

In [36]:
search(a,-3)

False

In [46]:
def my_max(items, key=None):
    if key is None:
        m = items[0]
        for i in items:
            if i > m:
                m=i
        return m
    else:
        m = items[0]
        for i in items:
            if key(i) > key(m):
                m = i
        return m

In [37]:
def last_name(name):
    return name.split()[-1]

In [49]:
names = ['John', 'Marraadar', 'dewradwed']

def max_vowels(name):
    max_vowel = 0
    for i in name:
        if i in 'ueoai':
            max_vowel += 1
    return max_vowel


m = my_max(names, key=max_vowels)
print(m)


Marraadar


In [52]:
print(numbers)

def max_last_digits(number):
    return number % 10

print(my_max(numbers, key=max_last_digits))

[93, 78, 63, 52, 51, 48, 40, 28, 23, 17]
78


In [60]:
#Find a number that has max sum of digits
print(numbers)

def sum_digits(x):
    return x % 10 + x // 10

print(my_max(numbers, key=sum_digits))


#Find number that has max abs value
numbers = [np.random.randint(-100, 100) for i in range(10)]
print(numbers)


print(my_max(numbers, key=abs))

[54, 55, 95, -8, -37, 51, 48, -95, -22, 6]
95
[-16, -89, 41, -32, 85, 80, -54, 93, 93, 30]
93
